#Embedding

In [29]:
import torch
from torch.nn import Embedding
n_embeddings, dim = 10,4
emb_1 = Embedding(n_embeddings,dim)
print(emb_1)

Embedding(10, 4)


In [30]:
emb_1.weight

Parameter containing:
tensor([[ 1.6600e+00,  3.8524e-02, -3.1800e-01, -1.5703e+00],
        [ 3.6272e-01,  1.1830e+00, -2.0510e+00, -1.2825e+00],
        [ 2.1823e-01,  1.3934e+00,  1.3752e+00, -7.3485e-01],
        [ 5.8897e-01, -9.5346e-01, -4.2578e-01, -8.0816e-01],
        [ 1.0399e+00,  1.4316e-03,  4.7158e-01,  4.5777e-01],
        [-1.2174e+00, -1.0017e-01,  3.1301e-01, -1.5984e+00],
        [-1.7990e-01, -1.7995e+00,  1.5364e+00,  1.0096e+00],
        [ 2.1356e-01,  8.4375e-01,  3.4835e-01,  3.0795e-02],
        [-1.0293e+00, -1.5987e+00, -2.0397e-01,  6.3090e-01],
        [-1.3517e+00,  1.7175e+00,  1.4640e-01, -2.7407e-01]],
       requires_grad=True)

In [31]:
inp = torch.LongTensor([[1,3], [5,5]])

emb_1(inp)

tensor([[[ 0.3627,  1.1830, -2.0510, -1.2825],
         [ 0.5890, -0.9535, -0.4258, -0.8082]],

        [[-1.2174, -0.1002,  0.3130, -1.5984],
         [-1.2174, -0.1002,  0.3130, -1.5984]]], grad_fn=<EmbeddingBackward0>)

In [5]:
inp

tensor([[1, 3],
        [5, 5]])

In [6]:
emb_1(inp).shape

torch.Size([2, 2, 4])

In [14]:
emb_2 = Embedding(n_embeddings,dim,padding_idx=5)

In [16]:
emb_2.weight

Parameter containing:
tensor([[-5.5879e-01, -2.0946e+00, -4.4645e-01,  1.2448e-01],
        [-2.1071e-02,  7.3077e-01, -5.2240e-01,  9.0087e-01],
        [ 1.0616e+00,  1.5841e+00,  9.1718e-01,  2.0405e-01],
        [ 5.0714e-01,  1.6676e-01,  1.4913e-01, -1.0088e+00],
        [ 4.0347e-01, -9.9291e-01, -1.5728e+00, -9.7593e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-4.4322e-01, -4.9805e-01, -4.2071e-01, -1.1849e+00],
        [ 9.7257e-01,  2.6768e-01,  7.9112e-01,  3.2167e-05],
        [ 2.6163e+00, -2.9761e-01,  4.9123e-01, -1.0441e+00],
        [ 8.5222e-01,  5.8406e-01, -9.3205e-02, -2.8341e-01]],
       requires_grad=True)

In [10]:
emb_2.weight.shape

torch.Size([10, 4])

In [20]:
emb_2(inp).mean().backward()

In [22]:
emb_2.weight.grad

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])

In [23]:
emb_3 = Embedding(n_embeddings,dim, norm_type=2, max_norm=1)

In [24]:
emb_3.weight

Parameter containing:
tensor([[-0.0111, -0.7134,  0.5512, -0.0063],
        [ 0.0189, -0.4237, -1.5268, -1.9800],
        [-1.5135, -0.4263, -1.4429, -0.9638],
        [-0.4427, -1.0986, -1.1211,  1.8040],
        [ 0.0866,  0.8058,  1.2283,  1.6450],
        [-1.3527, -0.2046, -1.5031,  1.9670],
        [ 0.2882, -0.8024,  1.3843,  0.6155],
        [-0.0775, -1.7851,  0.1311, -0.1907],
        [-0.9655, -1.0069,  1.2308,  1.0895],
        [ 0.2223, -0.0080,  1.3607, -0.9695]], requires_grad=True)

In [26]:
emb_3.weight.norm(dim=-1)

tensor([0.9017, 2.5360, 2.3416, 2.4319, 2.2072, 2.8284, 1.7384, 1.8017, 2.1560,
        1.6855], grad_fn=<LinalgVectorNormBackward0>)

In [27]:
emb_3(inp).norm(dim=-1)

tensor([[1.0000, 1.0000],
        [1.0000, 1.0000]], grad_fn=<LinalgVectorNormBackward0>)

In [28]:
emb_3.weight.norm(dim=-1)

tensor([0.9017, 1.0000, 2.3416, 1.0000, 2.2072, 1.0000, 1.7384, 1.8017, 2.1560,
        1.6855], grad_fn=<LinalgVectorNormBackward0>)

#SOFTMAX AND CROSS ENTROPY

In [15]:
import torch.nn as nn
import torch
import numpy as np
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis=1,keepdims=True)

x = np.array([[2,3,4,5],[1,2,3,4]])
x.shape
outputs = softmax(x)
print('softmax numpy: ', outputs)

softmax numpy:  [[0.0320586  0.08714432 0.23688282 0.64391426]
 [0.0320586  0.08714432 0.23688282 0.64391426]]


In [16]:
x = torch.tensor([2.0,3.0,4.0,5.0])
outputs = torch.softmax(x,dim=0)

In [5]:
outputs

tensor([0.0321, 0.0871, 0.2369, 0.6439])

In [ ]:
def cross_entropy(label, pred):
    return -np.sum(label*np.log(pred))


label = np.array([1.0,0,0])
pred_bad = np.array([0.6,0.3,1])
pred_good = np.array([0.1,0.8,0.1])
l1=cross_entropy(label, pred_bad)
l2 = cross_entropy(label, pred_good)
print(l1,l2)

0.5108256237659907 2.3025850929940455


In [21]:
loss = nn.CrossEntropyLoss()

Y = torch.tensor([0])
Y_pred_good = torch.tensor([[2.0,1.0,0.1]])
Y_pred_bad = torch.tensor([[0.6,0.3,1.0]])

l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)
print(l1.item(),l2)

0.4170299470424652 tensor(1.1733)


In [22]:
_, predictions1 = torch.max(Y_pred_good,1)
_, predictions2 = torch.max(Y_pred_bad,1)
print(predictions1, predictions2)

tensor([0]) tensor([2])


In [33]:
loss = nn.CrossEntropyLoss()

Y = torch.tensor([0,1,1])
Y_pred_good = torch.randint(10,(3,3),dtype = torch.float)

Y_pred_bad = torch.randint(10,(3,3),dtype = torch.float)

l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)
print(l1.item(),l2)

3.6167404651641846 tensor(3.4241)


In [34]:
_, predictions1 = torch.max(Y_pred_good,1)
_, predictions2 = torch.max(Y_pred_bad,1)
print(predictions1, predictions2)

tensor([2, 2, 1]) tensor([1, 0, 0])


In [38]:
class NeuralNet2( nn.Module):
    def __init__(self,input_size,hidden_size,num_classes):
        super(NeuralNet2,self).__init__()
        self.l1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.l2 = nn.Linear(hidden_size, num_classes)

    def forward(self,x):
        out = self.l1(x)
        out = self.relu(out)
        out = self.l2(out)
        return out
    
model = NeuralNet2(input_size = 28*28, hidden_size = 5, num_classes = 3)
criterion = nn.CrossEntropyLoss()

In [41]:
class NeuralNet2( nn.Module):
    def __init__(self,input_size,hidden_size):
        super(NeuralNet2,self).__init__()
        self.l1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.l2 = nn.Linear(hidden_size, 1)

    def forward(self,x):
        out = self.l1(x)
        out = self.relu(out)
        out = self.l2(out)
        y_pred = torch.sigmoid(out)

        return y_pred
    
model = NeuralNet2(input_size = 28*28, hidden_size = 5)
criterion = nn.BCELoss()
# sigmoid = nn.Si